### ISSUE TITLE
Compilation Albums?

### ISSUE THREAD

**Issue by krompus** [carnager/clerk#15]
When I browse the library by album, compilation albums are split up into individual "albums" based on the artist, despite all of the files being tagged correctly.

It seems that the album search is considering the artist as well as the album when searching albums.

The issue is not present in `ncmpcpp`.

Is there a configuration option that I could change, or is this a current limitation of the program?

**Comment by carnager** [comment]
cannot reproduce. for albums and latest views albumartist tag is used exclusively. artist tag is only used for tracks view.

**Comment by krompus** [comment]
Hmm. [Here's a screen shot.](http://i.imgur.com/cfITNei.png) I have `easytag` open to show the tags, ncmpcpp on the right showing the empty playlist, and clerk in the middle hovering over the album in question.

-- This actually isn't a compilation album, but it's another album that does this; same thing with compilations.

When I press enter on the album, it empties my playlist without adding the files. "Add" doesn't work either.

When I search `album artist` in ncmpcpp with the same criteria, the files are added without issue to the playlist.

Rofi itself works flawlessly; I had installed the main AUR package, and now I've switched to the github AUR package; the issue persists.

I just ran the script you gave me, and the albums I'm trying to play aren't on that list...indeed, all of the tracks I've tried to play that don't have an albumartist tag play just fine.

**Comment by carnager** [comment]
for clerk the albumartist tag is essential. It's a standard and you really should use it. 
I once had a artist fallback but i decided not to support mis-tagged files anymore. ALL albums should have an albumartist tag. i wrote a blog article about it: http://journal.53280.de/mpd.html

**Comment by krompus** [comment]
It's possible that you read this message before I made my edit. I can confirm that albums with correct albumartist tags do not work, and that at least some tracks (all the ones I've tried) that don't have the albumartist tag do not work.

So, I'm not sure what's going on here. I'm not trying to be contrarian, just forwarding my results. :)

(I'm tagging my files with `beets`, by the way, and it's doing an excellent job!)

**Comment by krompus** [comment]
I just read your blog post.

"ALL albums must have an albumartist tag"

...are you saying that there might be an issue with an album with correct tags if another album with incorrect tags is in the same music directory?

**Comment by carnager** [comment]
show me the output of the mpc command above

**Comment by krompus** [comment]
[Here you go.](https://gist.github.com/f7bf0ee14473bdf3fb17)

And, for comparison, [here's the output](https://gist.github.com/e84e6427eaac1c78c62e) without the `albumartist` filter.

**Comment by carnager** [comment]
i said mpc command...

**Comment by krompus** [comment]
Oh, you mean `mpc --format '[%albumartist%|%artist%]\t(%date%)\t%album%' search filename ''" | sort | uniq` ?

Err, not sure if I need to substitute anything in that line; [here it is bare.](https://i.imgur.com/k0d5w7K.png)

I also tried with "Kamasi" between the `'` `'`, and I got the same result.

**Comment by krompus** [comment]
(Sorry, closed by accident instead of submitting the comment)

**Comment by carnager** [comment]
if you know how to use IRC, it would really help if you could join freenode :p

Anyway, there is a quote too much. 
`mpc --format '[%albumartist%|MISSING] - %date% %album%' search filename '' | sort | uniq`

**Comment by krompus** [comment]
I'm on Freenode right now. #channel?

[Well, I think I've got the list of albums that won't play.](https://gist.github.com/ab2b2722492e9fe3ae4b)

I'll double check the tags, but there are still albums on that list that will play. Lots of the music that wouldn't play is on there, despite having valid albumartist tags. [The Disasterpeace albums won't run, for example; do you see anything wrong with the tags?](https://i.imgur.com/s7K0tBH.png)

**Comment by carnager** [comment]
you can find me on #gmpc or query Rasi

**Comment by carnager** [comment]
update: issue was solved. ${date_field} was set to "6" while his date tags required at least "12"

**Comment by krompus** [comment]
:)
