### ISSUE TITLE
Infinite random mode

### ISSUE THREAD

**Issue by Phyks** [carnager/clerk#16]
Hi,

Are there any plans (or are you interested in) putting an "infinite random" mode, playing random songs continuously, feeding new songs in the playlist when it is exhausted?

Thanks

**Comment by carnager** [comment]
this cannot be done in clerk, since clerk isn't constantly running to check the queue size, but a wrapper script is done easily. 

```
#!/bin/bash

mpc consume on

while true; do
    mpc idle player
    playlistsize=$(mpc playlist | wc -l)

    if [[ $playlistsize -eq "0" ]]; then
        clerk --random track
    fi
done
```

**Comment by Phyks** [comment]
Ok, I missed the fact that one could use clerk directly from the command line. Thanks! :)
