### ISSUE TITLE
Unable to add tracks with certain UTF-8 values in tags

### ISSUE THREAD

**Issue by zoqaeski** [carnager/clerk#17]
I've got David Bowie's ★ album, and it is tagged as such in the audio files. The tags are all from [MusicBrainz](https://musicbrainz.org/release-group/1fd18f5b-9a92-41fd-a590-da6b5cc60d85).

Clerk seems to refuse to add or insert any tracks from it, but refreshes anyway. Is there a way to debug Clerk to give you more information?

**Comment by carnager** [comment]
can't reproduce: https://fb.53280.de/swGAx/

bash -x /path/to/clerk might be helpful.

**Comment by carnager** [comment]
well, nearly a year without reply, I am closing this
