### ISSUE TITLE
When entering keybindings or selecting media, clerk flashes off and on momentarily.

### ISSUE THREAD

**Issue by krompus** [carnager/clerk#19]
I'm just wondering if this is intended / something that can't be avoided, or if there's a configuration setting I can change.

It's a very minor issue, but it would be nice to have the interface persist until exit.

**Comment by carnager** [comment]
rofi needs to restart, so thats not fixable. 
BUT... some actions can be done with multiple items. e.g. you can add/insert/replace multiple albums by simply using shift+enter to select albums. then use the normal hotkey on the last one.

**Comment by krompus** [comment]
Ah yes. I found the command: `rofi.kb-accept-custom:` in case anyone would like to remap it as I have. I've chosen `Control+i`, as I already have my pinky on the Control key when navigating.

I'll start using this then; thank you!
