### ISSUE TITLE
no track displayed

### ISSUE THREAD

**Issue by Tonus1** [carnager/clerk#21]
Hi,

Thanks for this great script.

It works quite fine playing random tracks with mpd but do not display any album nor track while trying to browse the library.

While it shows current queue when I choose to play random tracks. I couldn't find the reason.

Thanks for your help

Running slackware64-current
All dependencies met and up-to-date

**Comment by carnager** [comment]
What exactly did you try. What clerk normally should do:

Each time clerk detects that mpd database has changed, it will update its caches (~/.config/clerk/{tracks,albums,latest}.cache). Check if you have these files.

If you have, clerk --add {album,track,latest} should display the tracks/albums accordingly.
