### ISSUE TITLE
Back option

### ISSUE THREAD

**Issue by ibrokemypie** [carnager/clerk#23]
I might be missing things, but I can't seem to find any way to go back to the previous menu after entering an album etc. Any help?

**Comment by carnager** [comment]
there is Alt+F1/F2/F3 to switch to main views

**Comment by carnager** [comment]
in next version I might add a Cancel option to menus.

**Comment by carnager** [comment]
Since clerk does not have any navigation anymore since 4.0 (except for the tmux interface), i will close this
