### ISSUE TITLE
clerk won't launch rofi

### ISSUE THREAD

**Issue by fishman** [carnager/clerk#33]
How does clerk launch rofi? I see references to it in the code and i see the rvar{backend} = 'rofi' but there i can't get it to launch rofi.

**Comment by carnager** [comment]
see `clerk -h`
all arguments actually start rofi, except when using -f option.

**Comment by fishman** [comment]
Rasmus Steinke <notifications@github.com> writes:

> see clerk -h
> all arguments actually start rofi, except when using -f option.


I see that, but still for me it will only start tmux with fzf.

**Comment by carnager** [comment]
that's very strange indeed. I just tried what happens if no rofi is installed.

```
carnager@caprica ~ > rofi -t
zsh: command not found: rofi
```

as expected...

**Comment by fishman** [comment]
hmm is there anything special in your clerk.conf?

Rasmus Steinke <notifications@github.com> schrieb am So., 22. Okt. 2017 um
20:55 Uhr:

**Comment by carnager** [comment]
no...

```
[General]
# MPD_HOST will override this
mpd_host=tauron

# music root for rating_client
music_root=/mnt/wasteland/Audio/Rips

# define file paths
database=/home/carnager/.config/clerk/database.mpk
tmux_config=/home/carnager/.config/clerk/clerk.tmux

# player for queue tab
player=ncmpcpp

# number of songs clerk will get at once for creating its cache files
songs=20

# if mpd drops the connection while updating, reduce this.
chunksize=30000

# enable this to jump to queue after adding songs in tmux ui.
jump_queue=true

# Use albumartist or artist for random tracks?
randomartist=albumartist

# write tags to audio files. Needs running clerk_rating_client on machine with audio files
# ratings will always be written to sticker database.
tagging=false

[Columns]
# width of columns
albumartist_l=50
album_l=118
artist_l=66
date_l=6
title_l=50
track_l=2
rating_l=4

**Comment by carnager** [comment]
can you try ` clerk --no-tmux-ui -t`

**Comment by fishman** [comment]
that works

**Comment by carnager** [comment]
Ok, guess i will document that option, just in case. still strange :)

**Comment by eyadsibai** [comment]
same issue! would be nice to have it in the documentation
