### ISSUE TITLE
"Too many errors" when starting clerk

### ISSUE THREAD

**Issue by hgvhgv** [carnager/clerk#35]
I'm on MacOS 10.12.6 and installed clerk as user following the instructions. I get the following errors when launching `clerk` (I'm planning on using via tmux-fzf, not rofi, which I haven't tried to install). 

```
➜  ~ clerk.pl
"my" variable %rvar masks earlier declaration in same scope at /Users/hgv/bin/clerk.pl line 281.
Use of my $_ is experimental at /Users/hgv/bin/clerk.pl line 291.
Use of my $_ is experimental at /Users/hgv/bin/clerk.pl line 307.
"my" variable @_ masks earlier declaration in same scope at /Users/hgv/bin/clerk.pl line 307.
"my" variable $out masks earlier declaration in same scope at /Users/hgv/bin/clerk.pl line 310.
syntax error at /Users/hgv/bin/clerk.pl line 271, near "->%"
syntax error at /Users/hgv/bin/clerk.pl line 272, near "}"
Global symbol "@db" requires explicit package name at /Users/hgv/bin/clerk.pl line 272.
Global symbol "@filtered" requires explicit package name at /Users/hgv/bin/clerk.pl line 273.
syntax error at /Users/hgv/bin/clerk.pl line 274, near "}"
syntax error at /Users/hgv/bin/clerk.pl line 288, near "}"
syntax error at /Users/hgv/bin/clerk.pl line 304, near "}"
Global symbol "$filtered_db" requires explicit package name at /Users/hgv/bin/clerk.pl line 308.
syntax error at /Users/hgv/bin/clerk.pl line 313, near "}"
syntax error at /Users/hgv/bin/clerk.pl line 320, near "}"
/Users/hgv/bin/clerk.pl has too many errors.
```

Based on #2, it seems like at least someone got clerk working on macos/osx (though maybe that was the earlier, pre-perl version?). Maybe I need to install a different version of perl? I'm using the macos version, which is 5.18.2 (homebrew has a more recent version, but wanted to check here first as dealing with multiple versions can be a pain).

I was using clerk on arch before I recently switched back; would love to keep using it. Thanks!

**Comment by carnager** [comment]
perl 5.24 or later is needed.

**Comment by hgvhgv** [comment]
Got it running! Thanks so much. New version looks great!
