### ISSUE TITLE
Can't find queue window

### ISSUE THREAD

**Issue by Tonus1** [carnager/clerk#36]
Hi,
Awesome work with fzf and tmux, looks great ! I was used to rofi but will certainly switch soon.

I'm discovering tmux and might have missed something but I can't show the current queue : I've got a message that says "can't find window queue" (and it isn't showing next to albums, traks, playlists).

I'm running Slackware-current and use i3wm.

Btw, when I need the help window... I don't know how to hide it afterwards ! And a small tuto on how to use would have be a bit time saving, I didn't know how to launch at first (tmux -c './clerk.pl -f' if someone needs...)

Anyway, awesome work, Thank you very much !

**Comment by carnager** [comment]
queue window uses whatever player you have defined in config. default is ncmpcpp

**Comment by Tonus1** [comment]
Great, thank you @carnager !
Everything works now like a charm :)
