### ISSUE TITLE
Overwrite Rofi width and height

### ISSUE THREAD

**Issue by lukasgierth** [carnager/clerk#37]
I try to overwrite my default width and height for rofi which i set in Xresources. But there doesn't seem to be  an option for that anymore. Is that still possible? Otherwise the rofi frontend will be useless for me.

**Comment by carnager** [comment]
Can you try this? Either nuke your clerk.conf file or add this manually:

```
[Rofi]
width=default    
theme=default
```

**Comment by lukasgierth** [comment]
It does work! Thank you for adding that option.
