### ISSUE TITLE
Use rofi interface to find and play a given track

### ISSUE THREAD

**Issue by raphaelfournier** [carnager/clerk#39]
My Clerk installation went after an update from 3.2.1.1 to 4.0.5 (ArchLinux). I used clerk to find a track (`clerk --queue show`) and quickly launch it (ie: type a few letters, hit Enter, it plays, it's way more efficient than launching ncmpcpp and finding a track).
 
I read the changelog and saw the great revamp of the interface but I only see commands to Add/Insert/Replace a track or an album. I do not want to change the playing queue, just to navigate inside it, in a rofi-way. Is it possible? 

Edit: I found issue #24 , where you mention that the main playback queue interface may be removed, you probably did. I would welcome a work around, but that's OK if there's none. Thanks for your great work!

**Comment by carnager** [comment]
if anyone can build a clean queue interface i am open to merge it. The one in old clerk was basically unmaintainable and had lots of corner cases that didn't work the way they should.
if all you want is a list of songs in queue and select one, that can be archieved really easy:

```
#!/usr/bin/env bash                                                                                                                

menu=$(mpc playlist -f '%position%\t %artist%\t%title%\t%date% %album%' | column -t -s $'\t' -o $'\t' | rofi -dmenu -p '> ')
val=$?

id="$(echo "${menu}" | awk -F '\t' '{ print $1 }')"

if [[ $val -eq 1 ]]; then
    exit
else
    mpc play "${id}"
fi
```

**Comment by raphaelfournier** [comment]
Wow. Thank you very for giving me a full working program for my specific use case! You're very kind!
(I just tweaked a bit to truncate some fields and remove an unwanted space in `$id`).

I fully understand that a proper queue is not really doable. Long live clerk!
