### ISSUE TITLE
socket error

### ISSUE THREAD

**Issue by nicodebo** [carnager/clerk#42]
Hi,
I have no idea what happened but since a few days I have this message when typing "clerk" on the terminal:

"Error reading line from socket at /usr/bin/clerk line 268."

playing/pausing with mpc works fine.

**Comment by nicodebo** [comment]
well, I just found out that in mpd's log the following exception popped up when starting clerk:
```exception: error on client 13: Output buffer is full```

Solution was to increase the buffer size in the mdp.conf file by adding this line:
max_output_buffer_size "32768"  # (The default is 8192)

**Comment by carnager** [comment]
No need to change your mpd config. clerk has an option to get the database in multiple parts. Quote from config file:

```
# if mpd drops the connection while updating, reduce this.
chunksize=30000
```
