### ISSUE TITLE
Error while fetching lyrics

### ISSUE THREAD

**Issue by Tonus1** [carnager/clerk#44]
Hi all,
I don't know if that is new since I do not use very often this feature but I have erros on fetching well known lyrics with decent tags. I'm quite sure it has worked well...

Shall I correct my tags in some way ? Check for the version of dependencies that might have change their syntax ?

Thanks for every advice (I can't use another music player !)

Regards

**Comment by Tonus1** [comment]
Just started looking at this : seems that's all about ncmppcp... Still looking.

**Comment by carnager** [comment]
Yeah, default player in queue tab is ncmpcpp. Try to build ncmpcpp from git, maybe it helps. Also ncmpcpp has several lyrics providers, i think it's possible to disable certain ones, if they don't work
