### ISSUE TITLE
The file clerk_rating_client.service is shipped marked as executable

### ISSUE THREAD

**Issue by m040601** [carnager/clerk#49]
The file clerk_rating_client.service is marked executable as shipped from the github repo

Got this from my system log,

> Configuration file /usr/lib/systemd/user/clerk_rating_client.service is marked executable. Please remove executable permission bits. Proceeding anyway.

And indeed, installed on my system,

ls -l /usr/lib/systemd/user/clerk_rating_client.service

`-rwxr-xr-x 1 root root 157 Sep 18 17:45 /usr/lib/systemd/user/clerk_rating_client.service`

Of the many .service files there, clerk is the only one marked executable. All others are marked '-rw-r--r--'

**Comment by carnager** [comment]
I guess you are talking about the AUR package. The service file is not marked as executable on github, so it's a bug in the AUR package.
